import type { Role } from "@/modules/shared/types";

/**
 * Permission Matrix V1 (LOCKED) — FINAL-ARCHITECTURE.md §9.
 *
 * "ห้ามแก้ไขโดยไม่ได้รับการอนุมัติใหม่อย่างชัดเจน" — do not edit this file's role→permission
 * mapping without new, explicit approval. Some permissions below (e.g. reward/coupon/automation
 * management) have no corresponding feature yet — they exist so the Authorization Service is
 * ready for every later phase to consume without ever needing to touch the matrix again.
 */
export const PERMISSIONS = {
  MEMBER_VIEW: "member:view",
  MEMBER_SEARCH: "member:search",
  MEMBER_CREATE: "member:create",

  POINTS_ADD_RULE: "points:add_rule",
  POINTS_ADD_MANUAL: "points:add_manual",
  POINTS_ADJUST: "points:adjust",
  POINTS_REVERSE: "points:reverse",
  POINTS_VIEW_HISTORY: "points:view_history",

  REWARD_REDEEM: "reward:redeem",
  COUPON_REDEEM: "coupon:redeem",
  REWARD_MANAGE: "reward:manage",
  COUPON_MANAGE: "coupon:manage",
  PROMOTION_MANAGE: "promotion:manage",
  AUTOMATION_MANAGE: "automation:manage",

  BROADCAST_SEND: "broadcast:send",
  REPORT_VIEW: "report:view",
  STAFF_ACTIVITY_VIEW: "staff_activity:view",

  STAFF_MANAGE: "staff:manage",
  PERMISSION_MANAGE: "permission:manage",
  MERCHANT_SETTINGS_MANAGE: "merchant_settings:manage",
  BRANDING_MANAGE: "branding:manage",
  LINE_CONNECTION_MANAGE: "line_connection:manage",
  BILLING_MANAGE: "billing:manage",
  MERCHANT_LIFECYCLE_MANAGE: "merchant_lifecycle:manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ALL_PERMISSIONS = Object.values(PERMISSIONS) as Permission[];

/** Everything except the four explicit Owner-only powers (§9 Manager section). */
const MANAGER_PERMISSIONS = ALL_PERMISSIONS.filter(
  (p) =>
    p !== PERMISSIONS.PERMISSION_MANAGE &&
    p !== PERMISSIONS.LINE_CONNECTION_MANAGE &&
    p !== PERMISSIONS.BILLING_MANAGE &&
    p !== PERMISSIONS.MERCHANT_LIFECYCLE_MANAGE,
);

const STAFF_PERMISSIONS: Permission[] = [
  PERMISSIONS.MEMBER_VIEW,
  PERMISSIONS.MEMBER_SEARCH,
  PERMISSIONS.MEMBER_CREATE,
  PERMISSIONS.POINTS_ADD_RULE,
  PERMISSIONS.POINTS_ADD_MANUAL,
  PERMISSIONS.POINTS_VIEW_HISTORY,
  PERMISSIONS.REWARD_REDEEM,
  PERMISSIONS.COUPON_REDEEM,
];

export const ROLE_PERMISSIONS: Record<Role, ReadonlySet<Permission>> = {
  OWNER: new Set(ALL_PERMISSIONS),
  MANAGER: new Set(MANAGER_PERMISSIONS),
  STAFF: new Set(STAFF_PERMISSIONS),
};

/**
 * `permissionOverrides` on a StaffUser document (§5) grants permissions *in addition to* the
 * role default — it never revokes a role-default permission. Revocation/custom-role support is
 * an explicit Remaining Open Decision (§35 item 8), not V1 scope.
 */
export function hasPermission(
  role: Role,
  permission: Permission,
  permissionOverrides: readonly string[] = [],
): boolean {
  return (
    ROLE_PERMISSIONS[role].has(permission) ||
    (permissionOverrides as Permission[]).includes(permission)
  );
}
